m2

diff --git a/15-install_packages b/15-install_packages
--- a/15-install_packages
+++ b/15-install_packages
@@ -4,42 +4,53 @@ ID=$(id -u)
 TIMESTAMP=$(date +%F-%H-%M-%S)
 R="\e[31m"
 G="\e[32m"
+Y="\e[33m"
 N="\e[0m"
 
 LOG_FILE="/tmp/$0-$TIMESTAMP.log"
 
-#echo ("script started excecuted at $TIMESTAMP") &>> $LOG_FILE
+echo "script started excecuted at $TIMESTAMP" &>> $LOG_FILE
 
 VALIDATE()
 {
 if [ $1 -ne 0 ]
 then
 
-echo -e "installing  .. $2  is $R failed $N"
+echo -e "$2  is $R failed $N"
 exit1
 
 else
 
-echo -e "installing ..$2  is $G success $N"
+echo -e "$2  is $G success $N"
 fi
 }
 
 
 if [ $ID -ne 0 ]
 then
-     echo "ERROR: please run with root user"
+     echo -e "$R ERROR: please run with root user $N"
      exit 1
 else
      echo "you are in root user"
 fi
 
-yum install mysql -y &>> $LOG_FILE
+#echo "all arguments passed :$@"
+#git mysql postfix
+#package=git for first time
 
-VALIDATE $? "MYSQL"
+for package in $@
+do
+   yum list installed $package &>> $LOG_FILE #check installed or not
+   if [ $? -ne 0 ] # if not installed
+   then
+        yum install $package -y  &>> $LOG_FILE # install the package
+        VALIDATE $? "installation of $package" #validate
+    else
+        echo -e "$packge is already installed.. $Y skipping $N"
+    fi
+done 
 
-yum install git -y &>> $LOG_FILE
 
-VALIDATE $? "GIT"
 
 
 
